/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : SERVO1.c
**     Project     : adc_servo
**     Processor   : MK60FN1M0VLQ12
**     Component   : Servo
**     Version     : Component 01.066, Driver 01.00, CPU db: 3.00.000
**     Compiler    : CodeWarrior ARM C Compiler
**     Date/Time   : 2015-01-31, 12:49, # CodeGen: 1
**     Abstract    :
**
This component implements a driver for hobby servos.
**     Settings    :
**          Component name                                 : SERVO1
**          Inverted PWM                                   : no
**          Init PWM                                       : 1500
**          Min Pos PWM (us)                               : 600
**          Max Pos PWM (us)                               : 2500
**          PWM Period (us)                                : 20000
**          System                                         : 
**            Timed Move                                   : Disabled
**            Shell                                        : Disabled
**            PWM                                          : PWM
**     Contents    :
**         SetPWMDutyUs - void SERVO1_SetPWMDutyUs(word dutyUs);
**         SetPos       - void SERVO1_SetPos(byte pos);
**         PWMusToPos8  - byte SERVO1_PWMusToPos8(word us);
**         Init         - void SERVO1_Init(void);
**
**     License   :  Open Source (LGPL)
**     Copyright : (c) Copyright Erich Styger, 2013, all right reserved.
**     This an open source software implementing a driver for the 
**     Servo Motors using Processor Expert.
**     This is a free software and is opened for education,  research 
**     and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for
**       personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file SERVO1.c
** @version 01.00
** @brief
**
This component implements a driver for hobby servos.
*/         
/*!
**  @addtogroup SERVO1_module SERVO1 module documentation
**  @{
*/         

/* MODULE SERVO1. */

#include "SERVO1.h"
#define SERVO1_MIN_PWM_US          600 /*!< minimal duty cycle for servo */
#define SERVO1_MAX_PWM_US          2500 /*!< maximal duty cycle for servo */
#define SERVO1_INIT_PWM_US         1500 /*!< initial PWM duty */
#define SERVO1_PWM_PERIOD_US       20000 /*!< PWM period in micro seconds, typically 20'000 us (50 Hz) */
#define SERVO1_PWM_RANGE_US        (SERVO1_MAX_PWM_US-SERVO1_MIN_PWM_US) /*!< PWM range in micro seconds */
#define SERVO1_POS8_TO_PWM(pos)    (uint16_t)(SERVO1_MIN_PWM_US+(((pos)*(uint32_t)SERVO1_PWM_RANGE_US)/255)) /*!< Position to PWM transformation */
#define SERVO1_PWM_TO_POS8(pwm)    (uint16_t)((((uint32_t)(pwm)-SERVO1_MIN_PWM_US)*255/SERVO1_PWM_RANGE_US)) /*!< PWM to position transformation */
#define SERVO1_SHELL_NAME_STR      "SERVO1" /*!< Name used for servo in shell */

/* inverted PWM: if set to 1, then a duty value of 0xffff means signal is all time low, where 0x0000 means signal is high all time */
#define SERVO1_INVERTED_PWM   0

typedef struct SERVO1_ServoDescTag {
  uint16_t currPWMus; /* current duty in microseconds */
} SERVO1_ServoDesc;

/*! \brief Descriptor about the status of the servo */
static SERVO1_ServoDesc Servo;

/* Internal method prototypes */
static void DoSteps(void);

/*
** ===================================================================
**     Method      :  SERVO1_SetPWMDutyUs (component Servo)
**     Description :
**         Sets the servo PWM duty cycle in micro seconds (us)
**     Parameters  :
**         NAME            - DESCRIPTION
**         dutyUs          - Duty cycle in microseconds
**     Returns     : Nothing
** ===================================================================
*/
void SERVO1_SetPWMDutyUs(word dutyUs)
{
  /* write new duty cycle */
#if SERVO1_INVERTED_PWM
  Pwm1_SetDutyUS(SERVO1_PWM_PERIOD_US-dutyUs); /* need to invert duty cycle */
#else
  Pwm1_SetDutyUS(dutyUs);
#endif
  Servo.currPWMus = (uint16_t)dutyUs; /* update current duty cycle value */
}

/*
** ===================================================================
**     Method      :  SERVO1_SetPos (component Servo)
**     Description :
**         Sets the servo position
**     Parameters  :
**         NAME            - DESCRIPTION
**         pos             - Position to be used
**     Returns     : Nothing
** ===================================================================
*/
void SERVO1_SetPos(byte pos)
{
  SERVO1_SetPWMDutyUs((uint16_t)SERVO1_POS8_TO_PWM(pos));
}

/*
** ===================================================================
**     Method      :  SERVO1_Init (component Servo)
**     Description :
**         Moves the serve to its initialization position.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void SERVO1_Init(void)
{
  SERVO1_SetPWMDutyUs(SERVO1_INIT_PWM_US); /* set servo to initial duty ratio */
}

/*
** ===================================================================
**     Method      :  SERVO1_PWMusToPos8 (component Servo)
**     Description :
**         Transforms a micro-second PWM time into 8bit position
**     Parameters  :
**         NAME            - DESCRIPTION
**         us              - us PWM time
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
byte SERVO1_PWMusToPos8(word us)
{
  uint16_t pos, time;

  pos = SERVO1_PWM_TO_POS8(us);
  time = SERVO1_POS8_TO_PWM(pos);
  if (time<us) {
    return (byte)(pos+1); /* add rounding */
  } else {
    return (byte)pos;
  }
}

/* END SERVO1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
